# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/configuration-reference/ for more details.
#
version: 2.1

executors:
  humu-ci-docker-image:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.7.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

jobs:
  test:
    executor: humu-ci-docker-image
    working_directory: ~/repo
    steps:
      - checkout

      # Install dependencies, with caching.
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install_dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools cmake
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run_tests
          command: |
            . venv/bin/activate
            python setup.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports

  mypy:
    executor: humu-ci-docker-image
    working_directory: ~/repo
    steps:
      - checkout

      # Install dependencies, with caching.
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install_dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools mypy
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run_mypy
          command: |
            . venv/bin/activate
            mypy .

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  test:
    jobs:
      - test
      - mypy


# Only notify slack about build failures/fixes on master!
# https://discuss.circleci.com/t/only-notify-for-some-branches/10244
experimental:
  notify:
    branches:
      only:
        - master
