# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/configuration-reference/ for more details.
#
version: 2.1

executors:
  humu-ci-docker-image:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.7.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

jobs:
  test:
    executor: humu-ci-docker-image
    working_directory: ~/repo
    steps:
      - checkout
      # Ensure that pip and setuptools are up-to-date
      - run: pip3 install --upgrade pip setuptools
      # Build project and run megatest!
      - run: python setup.py test

workflows:
  version: 2
  test:
    jobs:
      - test


# Only notify slack about build failures/fixes on master!
# https://discuss.circleci.com/t/only-notify-for-some-branches/10244
experimental:
  notify:
    branches:
      only:
        - master
